export const SEARCH_BOOKMARKS_REQUESTED = "bookmarks/SEARCH_BOOKMARKS_REQUESTED";
export const SEARCH_BOOKMARKS_FULFILLED = "bookmarks/SEARCH_BOOKMARKS_FULFILLED";
export const SEARCH_BOOKMARKS_REJECTED = "bookmarks/SEARCH_BOOKMARKS_REJECTED";

export const LOAD_COMMITS_REQUESTED = "github/LOAD_COMMITS_REQUESTED";
export const LOAD_COMMITS_FULFILLED = "github/LOAD_COMMITS_FULFILLED";
export const LOAD_COMMITS_REJECTED = "github/LOAD_COMMITS_REJECTED";

export const ATT_REPOS = "github/ATT_REPOS";
export const SAVE_USER = "github/SAVE_USER";