export const SEARCH_BOOKMARKS_REQUESTED = "bookmarks/SEARCH_BOOKMARKS_REQUESTED";
export const SEARCH_BOOKMARKS_FULFILLED = "bookmarks/SEARCH_BOOKMARKS_FULFILLED";
export const SEARCH_BOOKMARKS_REJECTED = "bookmarks/SEARCH_BOOKMARKS_REJECTED";

export const CREATE_BOOKMARKS_REQUESTED = "bookmarks/CREATE_BOOKMARKS_REQUESTED";
export const CREATE_BOOKMARKS_FULFILLED = "bookmarks/CREATE_BOOKMARKS_FULFILLED";
export const CREATE_BOOKMARKS_REJECTED = "bookmarks/CREATE_BOOKMARKS_REJECTED";

export const DELETE_BOOKMARKS_REQUESTED = "bookmarks/DELETE_BOOKMARKS_REQUESTED";
export const DELETE_BOOKMARKS_FULFILLED = "bookmarks/DELETE_BOOKMARKS_FULFILLED";
export const DELETE_BOOKMARKS_REJECTED = "bookmarks/DELETE_BOOKMARKS_REJECTED";

export const DELETE_TAG_REQUESTED = "bookmarks/DELETE_TAG_REQUESTED";
export const DELETE_TAG_FULFILLED = "bookmarks/DELETE_TAG_FULFILLED";
export const DELETE_TAG_REJECTED = "bookmarks/DELETE_TAG_REJECTED";

export const BOOKMARK_UPDATED = "bookmarks/BOOKMARK_UPDATED";
export const FILTER_BOOKMARK = "bookmarks/FILTER_BOOKMARK";